### ISSUE TITLE
No version key warning since 2021.3

### ISSUE THREAD

**Issue by Dinges28** [jeroenterheerdt/HADailySensor#10]
After upgrading HA to version 2021.3, it comes with a logfile entry:

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'daily'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'daily'

Can you intergrate version keys to the custom components.

**Comment by jeroenterheerdt** [comment]
new release: https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v0.3.1
