### ISSUE TITLE
Redefinition caused abort

### ISSUE THREAD

**Issue by Harvsch** [jeroenterheerdt/HADailySensor#13]
I changed out some sensors, so I was redefining the daily sensors I use. I first deleted the daily sensors that were to be redefined. The first redefinition worked without problems. When I tried to redefine the second daily sensor, a dialog box saying "aborted" popped up. I tried restarting HA, but the problem persisted.
I noticed that the HA integrations screen froze after the attempted redefinition. Refreshing the page cleared the frozen screen.

**Comment by jeroenterheerdt** [comment]
did you see any error messages in the logs?
