### ISSUE TITLE
Ability to track non-numerical (Feature Request)

### ISSUE THREAD

**Issue by DeadEnded** [jeroenterheerdt/HADailySensor#2]
Hi!
I just saw your new component in HACS and was trying to use it in a slightly different case.
What I am wanting to achieve is to track how long a media player is in a specific state.  Would it be possible to set this up so you can track a specific state?

This might be beyond the design on this component, and that's okay - but I thought it would be worth asking 😄 .

For example, how long was a media player in the "playing" state.  Another use would be tracking how long a device was online or offline.  Do you think this is something you would be able to add to this sensor?

Thanks!
DeadEnd

**Comment by jeroenterheerdt** [comment]
I think this is out of scope of this component. Also, using a template sensor you should be able to go something like: `{{ (now().timestamp() - states.sensor.0x00158d00027bf7f5_click.last_updated.timestamp()) | timestamp_custom('%H:%M:%S', False) }}`, just copying this from https://community.home-assistant.io/t/display-how-long-ago-a-sensor-state-changed/190277/6

**Comment by DeadEnded** [comment]
Thanks, I'll take a look at that template sensor instead.
Wasn't sure what it would take and if this custom component would be able to do it.
I'll close this then.

Cheers!
DeadEnd
