### ISSUE TITLE
Edit parameters

### ISSUE THREAD

**Issue by szakacs-g** [jeroenterheerdt/HADailySensor#20]
Is there a way to edit / change parameters i.e. Interval without having to delete the entity and resubmiting ?

**Comment by jeroenterheerdt** [comment]
you can edit the files in the .storage hidden folder at your own risk

**Comment by maxnomo60** [comment]
i did find the hidden storag directory and also found the xxx.hacs file where general parameters are fixed. But no file to modify single daily-sensors.... Any way to do that ??  i just want to change period from 30 min down to 15 min for all sensors....

**Comment by maxnomo60** [comment]
Hi all, looked a bit deeper inside the hidden directory (best access is by SAMBA) 
..ha/config/.storage/core.config_entries
Here you can modify the daily sensor settings. Right ? For me it worked fine.

**Comment by maxnomo60** [comment]
Hi all, looked a bit deeper inside the hidden directory (best access is by SAMBA) 
..ha/config/.storage/core.config_entries
Here you can modify the daily sensor settings. Right ? For me it worked fine.

You can also modify the parameters inside HA with "developer tools".  Just select States and the desired entity.  Then ATTRIBUTES of the entity are displayed and can be modified !  (without dealing with hidden directories / files )

**Comment by jeroenterheerdt** [comment]
thanks, well if you change it in the developer tools AFAIK that's only for the current session and the settings will be overwritten with what you have in the hidden files on each reboot.

**Comment by FalconUK** [comment]
This is definitely a shortfall of this integration. I used customize to edit the interval.

`homeassistant:
 customize:
    sensor.outside_temperature_daily_minimum:
     interval: 1
     
    sensor.outside_temperature_daily_maximum:
     interval: 1`

**Comment by elyobelyob** [comment]
Could do with a simpler method TBF. Just started using this ...
