### ISSUE TITLE
how-to use

### ISSUE THREAD

**Issue by maxnomo60** [jeroenterheerdt/HADailySensor#24]
Hi, i am pretty new in HA and maybe too stupid. But i can not find how to set the parameters in config.YAML
The feature is exactlywhat i need. Pls where can,i find the how-to ?
Thx

**Comment by jeroenterheerdt** [comment]
hey, thanks for checking in. Not sure in which step you're having trouble. You should not have to touch your `configuration.yaml` for this as it is all configured in the UI (Integrations). See more in the readme https://github.com/jeroenterheerdt/HADailySensor

**Comment by glendower** [comment]
I also must be stupid as I cant get this to work, would it be possible to give an example of s sensor configuration. currently i have:

 - platform: daily
    entity: 
      - sensor.cotech_367959_72_f
    type: min
    name: new_min

where have I gone wrong?

**Comment by MarQua** [comment]
Hi, I've installed the integration but it's not clear to me where/how go on and configure the tool: my goal is to have the daily min-max temperature of some sensors. Regards, Marco

**Comment by jeroenterheerdt** [comment]
the readme clearly states what you need to do: https://github.com/jeroenterheerdt/HADailySensor#configuration. HA as a eco system is moving away from configuring in yam.
