### ISSUE TITLE
Add multiple attributes...

### ISSUE THREAD

**Issue by DavidFW1960** [jeroenterheerdt/HADailySensor#25]
This is looking like a great alternative to the average sensor that is broken and unsupported as of 2022.5
What I'd really like is to be able to have the state of the sensor say the average and also have minimum and maximum as attributes.

**Comment by jeroenterheerdt** [comment]
thanks - @DavidFW1960 why wouldn't you just create multiple sensors instead?

**Comment by DavidFW1960** [comment]
> thanks - @DavidFW1960 why wouldn't you just create multiple sensors instead?

Because I use the sensor with flex table card that will display attributes but not multiple sensors.
![image](https://user-images.githubusercontent.com/36390762/167240937-76eda0d9-98d7-4b1d-aebd-5297fc0e9e2a.png)

**Comment by jeroenterheerdt** [comment]
ok, interesting. If you are able, please feel free to make the required code changes in a PR.

**Comment by DavidFW1960** [comment]
I am not able..

**Comment by jeroenterheerdt** [comment]
min/max added in https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v2024.4.0
