### ISSUE TITLE
Unknown State Sensor

### ISSUE THREAD

**Issue by amagr0** [jeroenterheerdt/HADailySensor#28]
Hello,

I getting "unknown" state after config my first sensor.
Should I wait for a specific time to take effect?

![image](https://user-images.githubusercontent.com/12901952/172408022-e8876640-3990-4cb4-ae89-54db3255938b.png)

The sensor is working well:
![image](https://user-images.githubusercontent.com/12901952/172408706-2714cd21-ec1c-4b26-9a0d-d1de6e50161e.png)

HA: 2022.5.5

**Comment by jeroenterheerdt** [comment]
it should update after 30 minutes, since that is the `interval` you've got configured

**Comment by amagr0** [comment]
Hello @jeroenterheerdt,

It's working! Tks

Another question: I intent to create a sensor so I could see the max/min of temperatures of the day before, is that possible?

Thanks

**Comment by jeroenterheerdt** [comment]
unfortunately that is not possible with this component AFAIK
