### ISSUE TITLE
Tool does not find an existing sensor

### ISSUE THREAD

**Issue by kwithus** [jeroenterheerdt/HADailySensor#30]
I do have a min/max-Helper sensor with the name sensor.aussentemperatur
When I try to use this sensor as source for daily sensor, it always claims that one or more sensors do not exist and refuses to install the daily sensor 
Any idea?

**Comment by clydebarrow** [comment]
I have the same issue. When entering the sensor name, there is no drop-down matching what is typed as I would expect.

![Screenshot 2023-05-30 at 6 56 56 pm](https://github.com/jeroenterheerdt/HADailySensor/assets/2366188/46bcba86-287e-4ffb-98a2-6755c42133f7)
