### ISSUE TITLE
Sensor resets on HA restart

### ISSUE THREAD

**Issue by macmeck** [jeroenterheerdt/HADailySensor#32]
Currently, the sensor loses all historical data when HA is being restarted. Therefore, after a restart, the aggregation is not "daily" any more but only from after the time when HA has restarted.

Would it be possible to load the input sensor data from the database upon HA restart and start with a true daily calculation right away? Ideally using a configuration option whether to include historical data (load from DB upon start) or not (start blank)?

**Comment by ldsmovil** [comment]
it would be perfect

**Comment by Tntdruid** [comment]
My sensor does not reset when i restart HA.

**Comment by ldsmovil** [comment]
Value does not reset, time of this value does.

If min temp value is about 08.30 and you restart HA at 13.45, new min temp time value is 13.45.

**Comment by jeroenterheerdt** [comment]
it doesn't reset.
