### ISSUE TITLE
Feature Request: save the datetime the max/min occured at as an attribute 

### ISSUE THREAD

**Issue by lennon101** [jeroenterheerdt/HADailySensor#33]
As the title suggests: save the datetime the max/min occured at as an attribute to each sensor. This would be incredibly helpful for displaying (in the entity card etc) when the max/min etc occured. 
Please reply if you have any other questions about this. I love your work on this integration. Thanks!

**Comment by Herjan** [comment]
I have created PR #34 for this, hope this works for you!

**Comment by jeroenterheerdt** [comment]
integrated in https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v2024.4.0
