### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by dutchronnie** [jeroenterheerdt/HADailySensor#37]
Is it possible to give some examples how to use the dailysensor.
I want it to use for some temperature sensors, but i don't know how it works.

It's working now

**Comment by jeroenterheerdt** [comment]
do you still need help?

**Comment by dutchronnie** [comment]
Yes please,

I have come a littlebit futher, but stil having problems.

I have a temperature sensor added, but it says that it is not available.
But the temperature is displayed.

**Comment by jeroenterheerdt** [comment]
you install it in HACS. Then go to integrations and set it up. You select the entity and the aggregation (min/max/..) to apply. then the daily sensor should be created. if not, please show errors from the logs.
