### ISSUE TITLE
HA warning after update to 2023.5.2

### ISSUE THREAD

**Issue by armin-gh** [jeroenterheerdt/HADailySensor#38]
Hi
after updating my HA to 2023.5.2 this warning is shown in the logs:
` Entity sensor.fritz7490mindailysent (<class 'custom_components.daily.sensor.DailySensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
`
Using HA core installation in Python VENV with Python 3.10

Armin

**Comment by marcel-sch** [comment]
please check [https://github.com/jeroenterheerdt/HADailySensor/pull/36](url)

**Comment by Kaibob2** [comment]
Removing` @asyncio.coroutine` in sensor.py doesn't fix this issue for me.

**Comment by armin-gh** [comment]
Hi
removing @asyncio.coroutine does not fix this warning, it fixes another issue ( #035 ) with this custom integration after updating to Python 3.11, if you do not remove @asyncio.coroutine,  the integration does not start at all.

**Comment by jeroenterheerdt** [comment]
new release: https://github.com/jeroenterheerdt/HADailySensor/releases/tag/v0.4.0
