### ISSUE TITLE
FR: Daily sensor for previous day

### ISSUE THREAD

**Issue by giggo** [jeroenterheerdt/HADailySensor#4]
Thanks for this great integration. Helped me to get rid of multiple helpers and Node Red flows.
Any plans to add a daily sensor for the PREVIOUS day as well?

**Comment by jeroenterheerdt** [comment]
no, I have no scenario for it - but the code is simple, you can easily add it in.

**Comment by Vartkat** [comment]
Hi, 

I don't know about @giggo but I'm no coder so I don't know how to do it and I would like to clarify something,: doesn this intégration makes the recorder keep values per day ? I understand the reset at midnight but I'm confused by how does this behave on the recording side .

Thanks for the help

V.
