### ISSUE TITLE
Delete a sensor possible?

### ISSUE THREAD

**Issue by JBecker32** [jeroenterheerdt/HADailySensor#44]
I am not able to delete a daily sensor. Is there a way to achieve this (apart from deleteing it in the .storage/core.config_entries)?

**Comment by jeroenterheerdt** [comment]
you should be able to just delete it from the integrations UI.

**Comment by JBecker32** [comment]
Yes, this is perfectly true!
I am stupid that I didn't find it!
Best regards, Jörg.
