### ISSUE TITLE
Expected float error in the Refresh interval

### ISSUE THREAD

**Issue by lennon101** [jeroenterheerdt/HADailySensor#47]
Not entirely sure what is going on here. I just tried creating a new sensor and got this error. Am I entering the values incorrectly or is this a bug? See the screenshot for more information. HA version: core-2024.4.0

![image](https://github.com/jeroenterheerdt/HADailySensor/assets/1709944/d3558f9a-6e4b-475b-97ed-2dec50098448)

**Comment by jeroenterheerdt** [comment]
can you try writing 30.0? This might be due to allowing < 1 minute intervals..

**Comment by jeroenterheerdt** [comment]
should be fixed in 2024.4.2
