### ISSUE TITLE
How to change interval back to minutes again

### ISSUE THREAD

**Issue by magfro** [jeroenterheerdt/HADailySensor#48]
After upgrading to v2024.42 my sensors update every 30 second instead of every 30 minute (mentioned in the changelog as a breaking change, but not updated in the README btw...).

How do I reconfigure my sensors? I can't find any way to do that in the UI.

**Comment by Petorrr** [comment]
Same here, not nice to delete sensors as you will lose the history….. I have multiple max sensors for monthly or even yearly and would like to keep those values. Any other workaround to fix this and get back to the original checking interval?

**Comment by jeroenterheerdt** [comment]
just edit the storage file and you're done.

**Comment by jeroenterheerdt** [comment]
Or. Just install the previous version.

**Comment by magfro** [comment]
For anyone else coming here looking for answers, here is how I solved the issue in my installation:

1. In Home Assistant's config folder, open the hidden folder `.storage`. 
2. Open the file `core.config_entries` in that folder with a text editor. 

    **NOTE: Please do a backup before changing anything in this file, as issues with the formatting will likely prevent Home Assistant from ever booting up again!**
    
3. Search for the line: `"domain": "daily",` and make sure the title or name is the same as the name of your Daily sensor.
4. In the same JSON, change the `interval` to the desired number of seconds. If you have 30 (minutes) here, just change it to 1800 (seconds).
5. Restart Home assistant for the changes to take effect.

Hope this helps someone else.
//Magnus
