### ISSUE TITLE
Add validation in source input.

### ISSUE THREAD

**Issue by parislyon69** [jeroenterheerdt/HADailySensor#53]
Is there a way to automatically populate the entity field with a droplist of choices and a droplist of choices for the unit if measurement. In my opinion this would greatly increase usability of your excellent work

Bedankt

G

**Comment by jeroenterheerdt** [comment]
Entity is hard as it would be long long list of all sensors or input_numbers, so ehh, no. For units drop downs already exist? Or did I miss some? Can you share a screenshot of where you think it would help?

**Comment by parislyon69** [comment]
I was just thinking it could be the same drop-down entity list with a small
search box on top, as we see in plenty other integrations. It would save a
lot of copy-paste, and much easier of newbies

But it is upto you thanks for your answer


Gideon Smolders

**Comment by jeroenterheerdt** [comment]
Happy to investigate of course. Do you have an integration in mind that does this in a way you think works well? Thank you!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by parislyon69** [comment]
I guess easiest is to navigate jn your HA to create helpers, select
derivative sensors and in the select entity it shows a nice drop-down

Hope this helps.

**Comment by parislyon69** [comment]
Sorry to keep bothering you.

I added some sensors yesterday, and it took midnight for it to actually
update. Is that normal? I actually thought the sensor would record any
value higher than the previous high, and resets at midnight?

So it should keep changing higher during the day and retain the highest
value until midnight, correct?

I àm sure it is just my muddled brain that is confusing things.

Merci

Gideon

**Comment by parislyon69** [comment]
Yes thank you, my non functioning brain again....

Let me know if you decide to get a drop down list. I will the migrate my
existing sensors, that are currently sitting in yaml files. But I think a
front end solution is way better. Bug I am dreading the copy pasting 😜

**Comment by jeroenterheerdt** [comment]
Happy to build a drop down list, but if you can point to an integration that has done that nicely, let me know. I don’t have to time to figure this out so would rather just steal someone else’s solution.

**Comment by parislyon69** [comment]
OK sounds great already.
Thanks for your quick reaction and time.

**Comment by jeroenterheerdt** [comment]
validation is already there, closing this because we're not going to go add a dropdown.
