### ISSUE TITLE
 Automatically reset at 00:00 is not working

### ISSUE THREAD

**Issue by ErikOberle** [jeroenterheerdt/HADailySensor#61]
Automatically reset at 00:00 is checked and it was working pretty good. 
Unfortunately, the reset of the value at 0:00 has not been working properly for some time.
Box is checked.
![Unbenannt1](https://github.com/jeroenterheerdt/HADailySensor/assets/154922279/7bd8f661-c9e7-4662-9fa1-2d82d5771cff)
![Unbenannt2](https://github.com/jeroenterheerdt/HADailySensor/assets/154922279/135829f2-b80a-40b6-b4fd-c0070edb9df7)
The low value between 0 and 6 am is probably due to the fact that the WLAN is deactivated at 0.15 am. However, this has always been the case and the reset at 0.00 a.m. also worked.

**Comment by jeroenterheerdt** [comment]
which HA version are you on? is there anything in the logs?

**Comment by ErikOberle** [comment]
Please excuse the late reply. The tip about the HA version was good. I
updated to the latest version and it works fine again. Thank you very much.

Am Sa., 6. Juli 2024 um 23:43 Uhr schrieb Jeroen ter Heerdt <
***@***.***>:
