### ISSUE TITLE
It is not clear how to configure

### ISSUE THREAD

**Issue by Lvdvvdk** [jeroenterheerdt/HADailySensor#67]
I downloaded the component in ha 2024.9.3 and after a reboot I see a new "Daily sensor" device in HACS, but no new integration is visible in Settings->Integrations.
So how to configure this component?

[config_entry-hacs-bb754784f5d610372c323b0b45536b7b.json](https://github.com/user-attachments/files/17150666/config_entry-hacs-bb754784f5d610372c323b0b45536b7b.json)

**Comment by jeroenterheerdt** [comment]
clear your browser cache and try to find the integration again.
