### ISSUE TITLE
The unit of measurement 

### ISSUE THREAD

**Issue by fontes31** [jeroenterheerdt/HADailySensor#9]
Hi,

Iam trying to configure daily sensor on HA. 
The entity is ok, i use one of the netatmo sensor
my doubt is the unit of measurement - what i add here?
refresh interval i add 5 min
![daily](https://user-images.githubusercontent.com/7975962/98299311-6fc74400-1faf-11eb-958f-a43e0b847c79.JPG)

I choose "C" but i cannot get any value on the max temperature

**Comment by jeroenterheerdt** [comment]
weird, I am using very similar configuration:
```
"interval": 1,
"name": "Maximum Temperature",
"operation": "max",
"sensor": "sensor.smartweather_temperature",
"unit_of_measurement": "F"
```

you should be able to just enter whatever you want for `unit_of_measurement`.
Are you sure the input sensor you use is of the right data type? any errors in the log?

**Comment by fontes31** [comment]
Iam using the input sensor of netatmo that stopped working, temperature maximum and minimum:

And if i use those sensors it will continue not working. So, how can i fix this?

Correct, it works if i use the sensors that are working, fact

**Comment by jeroenterheerdt** [comment]
I am not sure if I understand what you mean.
